FROM ubuntu:latest
RUN  apt-get update
RUN  apt-get --assume-yes install wget
RUN  wget https://download.java.net/java/GA/jdk9/9.0.4/binaries/openjdk-9.0.4_linux-x64_bin.tar.gz
RUN  tar -zxvf openjdk-9.0.4_linux-x64_bin.tar.gz
COPY java/DockerTest.class /
CMD  /jdk-9.0.4/bin/java ${JAVA_OPT} DockerTest ${APP_OPT}