Vagrant.configure("2") do |config|
  config.vm.guest = :linux
  config.vm.box = "fedora/31-cloud-base"
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = 2048
    v.cpus = 2
    v.name = "Fedora Linux Desktop"
    v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    v.customize ["storageattach", :id, 
                  "--storagectl", "IDE", 
                  "--port", "0", "--device", "1", 
                  "--type", "dvddrive", 
                  "--medium", "emptydrive"]  
    v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    #v.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    v.customize ["modifyvm", :id, "--hwvirtex", "on"]
    v.customize ["modifyvm", :id, "--vram", "128"]
  end
  # In case you need an IP to access the VM from another software :
  # config.vm.network "private_network", ip: "192.168.56.101"

  # For ubuntu guest
  config.vm.provision :shell, :path => "scripts/run_on_fedora.sh"
  config.vm.provision :reload
end