## How to build and push this image

# docker build -t sunnyvale/resource-tester:1.0 . 
# docker login
# docker push sunnyvale/resource-tester:1.0

FROM ubuntu:latest

RUN apt-get update -y && \
    apt-get install -y stress-ng && \
    apt-get install -y stress



